// Generated by scripts/generate-release-projections.mjs. Do not edit by hand.

import type { KmindReleaseChangelogItem } from "@kmind/app";

export const OBSIDIAN_UPDATE_DIALOG_RELEASES_ZH: KmindReleaseChangelogItem[] = [
  {
    version: "0.22.0",
    releasedAt: "2026-07-08T00:00:00.000Z",
    locale: "zh-CN",
    title: "大括号连线与导入导出增强",
    tags: [
      "feature",
      "fix",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.22.0-brace-edge-style",
            text: "新增大括号连线风格，当前的布局方式均可用。"
          },
          {
            id: "obsidian-0.22.0-structure-import-formats",
            text: "新增 .md / .opml / .txt / .mm (FreeMind) 文件格式导入支持。"
          },
          {
            id: "obsidian-0.22.0-structure-export-formats",
            text: "新增 .md / .opml / .mm / .xmind 文件格式导出支持。"
          }
        ]
      },
      {
        kind: "fix",
        title: "修复",
        items: [
          {
            id: "obsidian-0.22.0-remove-lecture-export-options",
            text: "移除暂未完全适配的知识讲义系列导出支持项。"
          }
        ]
      },
      {
        kind: "other",
        title: "其它",
        items: [
          {
            id: "obsidian-0.22.0-core-whiteboard-elements",
            text: "升级内核版本，为即将到来的白板元素做准备。"
          },
          {
            id: "obsidian-0.22.0-core-performance",
            text: "优化内核性能。"
          }
        ]
      }
    ]
  },
  {
    version: "0.21.0",
    releasedAt: "2026-07-03T00:00:00.000Z",
    locale: "zh-CN",
    title: "节点拖拽对齐辅助线",
    tags: [
      "feature",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.21.0-node-drag-alignment-guides",
            text: "新增节点拖拽对齐辅助线。"
          }
        ]
      },
      {
        kind: "other",
        title: "其它",
        items: [
          {
            id: "obsidian-0.21.0-core-whiteboard-elements",
            text: "升级内核版本，为即将到来的白板元素做准备。"
          }
        ]
      }
    ]
  },
  {
    version: "0.20.0",
    releasedAt: "2026-06-29T00:00:00.000Z",
    locale: "zh-CN",
    title: "滚轮行为偏好",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.20.0-wheel-behavior-setting",
            text: "插件设置 -> 画布操作习惯中新增“滚轮行为”，提供“直接缩放”“滚轮平移，按 Ctrl/Cmd 缩放”“关闭滚轮缩放”三个选项。"
          },
          {
            id: "obsidian-0.20.0-wheel-pan-mode",
            text: "选择“滚轮平移，按 Ctrl/Cmd 缩放”后，普通纵向滚轮上下平移，横向滚轮或 Shift + 纵向滚轮左右平移，Ctrl/Cmd + 滚轮缩放。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "改进",
        items: [
          {
            id: "obsidian-0.20.0-wheel-default",
            text: "默认滚轮行为保持为直接缩放，不改变既有用户操作习惯。"
          }
        ]
      }
    ]
  },
  {
    version: "0.19.0",
    releasedAt: "2026-06-28T00:00:00.000Z",
    locale: "zh-CN",
    title: "枝干线与树状布局",
    tags: [
      "feature",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.19.0-tree-layouts",
            text: "新增布局：向上树状图 & 向下树状图。"
          },
          {
            id: "obsidian-0.19.0-ink-branch-theme",
            text: "新增简洁主题：墨线枝干。",
            media: [
              {
                type: "png",
                url: "https://s312g.malibu.root233.com/picbed/2026/06/98fe914a43cd46effe1079193f2a4697.png",
                posterUrl: "https://s312g.malibu.root233.com/picbed/2026/06/98fe914a43cd46effe1079193f2a4697.png",
                alt: "墨线枝干主题预览"
              }
            ]
          },
          {
            id: "obsidian-0.19.0-branch-line-route",
            text: "新增连线风格：枝干线，该风格在主题设计器中也能用啦～"
          }
        ]
      },
      {
        kind: "other",
        title: "其它",
        items: [
          {
            id: "obsidian-0.19.0-core-layout-engine",
            text: "更新内核布局引擎。"
          }
        ]
      }
    ]
  },
  {
    version: "0.18.0",
    releasedAt: "2026-06-27T00:00:00.000Z",
    locale: "zh-CN",
    title: "节点结构快捷操作",
    tags: [
      "feature",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.18.0-add-parent-context-menu",
            text: "新增节点右键菜单「添加父节点」与对应快捷键配置。"
          },
          {
            id: "obsidian-0.18.0-move-node-shortcuts",
            text: "新增上移节点、下移节点功能，快捷键为 `Alt/Option+Up`、`Alt/Option+Down`。"
          },
          {
            id: "obsidian-0.18.0-collapse-expand-shortcuts",
            text: "新增收缩、展开节点快捷键：`Alt/Option+Left`、`Alt/Option+Right`。"
          }
        ]
      },
      {
        kind: "other",
        title: "其它",
        items: [
          {
            id: "obsidian-0.18.0-core-version",
            text: "更新内核版本。"
          }
        ]
      }
    ]
  },
  {
    version: "0.17.1",
    releasedAt: "2026-06-25T00:00:00.000Z",
    locale: "zh-CN",
    title: "更新弹框官方内容加载修复",
    tags: [
      "fix"
    ],
    sections: [
      {
        kind: "fix",
        title: "修复",
        items: [
          {
            id: "obsidian-0.17.1-official-content-cors",
            text: "修复更新弹框右侧官方内容在 Obsidian 中因跨源请求限制而加载失败的问题。"
          }
        ]
      }
    ]
  },
  {
    version: "0.17.0",
    releasedAt: "2026-06-25T00:00:00.000Z",
    locale: "zh-CN",
    title: "更新日志弹框与快捷键优化",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.17.0-update-dialog-and-changelog",
            text: "新增更新日志弹框与官网更新日志，支持查看本次更新内容和以往更新。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.17.0-remove-plugin-ctrl-n",
            text: "移除插件端 Ctrl/Cmd+N 默认快捷键，避免覆盖 Obsidian 或系统的新建行为。"
          }
        ]
      }
    ]
  },
  {
    version: "0.16.0",
    releasedAt: "2026-06-23T00:00:00.000Z",
    locale: "zh-CN",
    title: "原地节点编辑体验优化",
    tags: [
      "feature",
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "feature",
        title: "节点编辑",
        items: [
          {
            id: "obsidian-0.16.0-inline-node-editing",
            text: "重构节点编辑体验，支持真正的原地编辑，编辑区保持在节点正文内部，交互更稳定顺滑。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "编辑体验",
        items: [
          {
            id: "obsidian-0.16.0-first-line-multiline-zoom",
            text: "优化首行输入、多行增长、缩放和混合字号等场景下的编辑交互与性能。"
          },
          {
            id: "obsidian-0.16.0-disable-spellcheck",
            text: "关闭节点正文、备注和大纲编辑中的拼写检查，减少浏览器或宿主写作辅助对导图编辑的干扰。"
          }
        ]
      },
      {
        kind: "fix",
        title: "导出稳定性",
        items: [
          {
            id: "obsidian-0.16.0-export-text-clipping",
            text: "修复极端情况下导出 PNG 或 SVG 时节点正文被截断的问题。"
          }
        ]
      }
    ]
  },
  {
    version: "0.15.0",
    releasedAt: "2026-06-22T00:00:00.000Z",
    locale: "zh-CN",
    title: "新增节点宽度拖拽手柄，可在画布中直接调整节点内容宽度",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.15.0-feature-1",
            text: "新增节点宽度拖拽手柄，可在画布中直接调整节点内容宽度。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.15.0-improvement-1",
            text: "优化极端内容下的节点宽度测量，减少密集文本、公式、inline code 和导出场景中的节点内容裁剪问题。"
          }
        ]
      }
    ]
  },
  {
    version: "0.14.1",
    releasedAt: "2026-06-22T00:00:00.000Z",
    locale: "zh-CN",
    title: "对齐 Obsidian 大纲 / 分屏行控件与 WebApp 视觉，移除宿主按钮样式带来的白色背景和内阴影",
    tags: [
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.14.1-improvement-1",
            text: "对齐 Obsidian 大纲 / 分屏行控件与 WebApp 视觉，移除宿主按钮样式带来的白色背景和内阴影。"
          }
        ]
      },
      {
        kind: "fix",
        title: "修复",
        items: [
          {
            id: "obsidian-0.14.1-fix-1",
            text: "修复 Obsidian 大纲行右键菜单定位，菜单会贴近当前行打开，不再偏到很右侧。"
          }
        ]
      }
    ]
  },
  {
    version: "0.14.0",
    releasedAt: "2026-06-20T00:00:00.000Z",
    locale: "zh-CN",
    title: "新增大纲与分屏模式，可在导图、大纲、分屏之间切换",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.14.0-feature-1",
            text: "新增大纲与分屏模式，可在导图、大纲、分屏之间切换。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.14.0-improvement-1",
            text: "同一份导图可在连续大纲中编辑，选中、富文本、概要、图标和快捷键与导图保持同步。"
          },
          {
            id: "obsidian-0.14.0-improvement-2",
            text: "分屏模式支持导图节点与大纲双向拖拽，可从大纲拖到导图，也可从导图拖回大纲。"
          }
        ]
      }
    ]
  },
  {
    version: "0.13.0",
    releasedAt: "2026-06-14T00:00:00.000Z",
    locale: "zh-CN",
    title: "优化 节点关联线 编辑器，优化智能避让功能",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.13.0-feature-1",
            text: "新增三种关联线类型：直线，正交连线，圆角正交连线。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.13.0-improvement-1",
            text: "优化 节点关联线 编辑器，优化智能避让功能。"
          }
        ]
      }
    ]
  },
  {
    version: "0.12.1",
    releasedAt: "2026-06-12T00:00:00.000Z",
    locale: "zh-CN",
    title: "修复待办右键菜单快捷键提示",
    tags: [
      "fix"
    ],
    sections: [
      {
        kind: "fix",
        title: "修复",
        items: [
          {
            id: "obsidian-0.12.1-fix-1",
            text: "修复待办右键菜单快捷键提示。"
          }
        ]
      }
    ]
  },
  {
    version: "0.12.0",
    releasedAt: "2026-06-12T00:00:00.000Z",
    locale: "zh-CN",
    title: "新增右键按层级展开，可将节点或当前导图展开到 1-6 层",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.12.0-feature-1",
            text: "新增右键按层级展开，可将节点或当前导图展开到 1-6 层。"
          },
          {
            id: "obsidian-0.12.0-feature-2",
            text: "新增节点子树和当前导图的快速展开 / 收起入口。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.12.0-improvement-1",
            text: "当前导图收起后，右键菜单会自动切换为展开当前导图。"
          }
        ]
      }
    ]
  },
  {
    version: "0.11.2",
    releasedAt: "2026-06-04T00:00:00.000Z",
    locale: "zh-CN",
    title: "更新插件市场 manifest 描述",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.11.2-improvement-1",
            text: "更新插件市场 manifest 描述"
          }
        ]
      }
    ]
  },
  {
    version: "0.11.1",
    releasedAt: "2026-06-03T00:00:00.000Z",
    locale: "zh-CN",
    title: "优化 Obsidian 插件文案",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.11.1-improvement-1",
            text: "优化 Obsidian 插件文案。"
          },
          {
            id: "obsidian-0.11.1-improvement-2",
            text: "优化快速上手和插件市场展示说明。"
          },
          {
            id: "obsidian-0.11.1-improvement-3",
            text: "打磨交互文案和插件展示细节。"
          }
        ]
      }
    ]
  },
  {
    version: "0.11.0",
    releasedAt: "2026-05-21T00:00:00.000Z",
    locale: "zh-CN",
    title: "新增画布拖拽习惯设置，可在平移优先和选择优先之间切换",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.11.0-feature-1",
            text: "新增画布拖拽习惯设置，可在平移优先和选择优先之间切换。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.11.0-improvement-1",
            text: "选择优先模式下，导图空白处左键拖拽框选，按 Space + 左键拖拽平移画布。"
          },
          {
            id: "obsidian-0.11.0-improvement-2",
            text: "Space 会保留给画布导航使用，避免自定义快捷键影响平移操作。"
          }
        ]
      }
    ]
  },
  {
    version: "0.10.0",
    releasedAt: "2026-05-21T00:00:00.000Z",
    locale: "zh-CN",
    title: "插件端新增插入图片自动压缩配置，默认开启",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.10.0-improvement-1",
            text: "插件端新增插入图片自动压缩配置，默认开启。"
          },
          {
            id: "obsidian-0.10.0-improvement-2",
            text: "节点图片新增直接拖动调整大小。"
          },
          {
            id: "obsidian-0.10.0-improvement-3",
            text: "节点图片支持拖拽到上、下、左、右方位。"
          }
        ]
      }
    ]
  },
  {
    version: "0.9.1",
    releasedAt: "2026-05-20T00:00:00.000Z",
    locale: "zh-CN",
    title: "优化 dark 模式下的节点编辑和富文本备注编辑体验",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.9.1-improvement-1",
            text: "优化 dark 模式下的节点编辑和富文本备注编辑体验。"
          },
          {
            id: "obsidian-0.9.1-improvement-2",
            text: "优化富文本工具栏下拉、链接 / 挖空 / 斜杠 / 公式浮层和右键菜单滚动条的 dark 适配。"
          },
          {
            id: "obsidian-0.9.1-improvement-3",
            text: "优化关联线添加和格式刷的鼠标跟随提示的 dark 适配。"
          }
        ]
      }
    ]
  },
  {
    version: "0.9.0",
    releasedAt: "2026-05-18T00:00:00.000Z",
    locale: "zh-CN",
    title: "优化概要节点 i18n 和交互细节",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.9.0-feature-1",
            text: "新增批量节点拖拽：多选节点后，按住任意已选中节点即可整体移动。"
          },
          {
            id: "obsidian-0.9.0-feature-2",
            text: "新增初次创建导图时，节点自动居中的功能。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.9.0-improvement-1",
            text: "优化概要节点 i18n 和交互细节。"
          }
        ]
      }
    ]
  },
  {
    version: "0.8.0",
    releasedAt: "2026-05-18T00:00:00.000Z",
    locale: "zh-CN",
    title: "优化关联线功能与交互，新增虚线 / 点线样式选择",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.8.0-feature-1",
            text: "新增关联线颜色配置，让跨分支关系表达更清晰。"
          },
          {
            id: "obsidian-0.8.0-feature-2",
            text: "新增项目级别关联线配置，便于整张导图保持统一的关联线风格。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.8.0-improvement-1",
            text: "优化关联线功能与交互，新增虚线 / 点线样式选择。"
          },
          {
            id: "obsidian-0.8.0-improvement-2",
            text: "为概要新增关联线支持。"
          }
        ]
      }
    ]
  },
  {
    version: "0.7.0",
    releasedAt: "2026-05-17T00:00:00.000Z",
    locale: "zh-CN",
    title: "普通 PNG 导出新增图片美化能力，当前开放简洁窗口外框风格",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.7.0-improvement-1",
            text: "普通 PNG 导出新增图片美化能力，当前开放简洁窗口外框风格。"
          },
          {
            id: "obsidian-0.7.0-improvement-2",
            text: "导出弹窗新增 PNG 清晰度选择，可在文件体积和图片清晰度之间按需取舍。"
          },
          {
            id: "obsidian-0.7.0-improvement-3",
            text: "画布和节点右键“复制为图片”升级为带预览的样式选择，支持原图和窗口外框图片。"
          },
          {
            id: "obsidian-0.7.0-improvement-4",
            text: "优化右键菜单二级菜单的悬停宽限。"
          }
        ]
      }
    ]
  },
  {
    version: "0.6.0",
    releasedAt: "2026-05-15T00:00:00.000Z",
    locale: "zh-CN",
    title: "可以直接在 Obsidian 插件中设计并保存本地 KMind Zen 主题",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.6.0-feature-1",
            text: "可以直接在 Obsidian 插件中设计并保存本地 KMind Zen 主题。"
          },
          {
            id: "obsidian-0.6.0-feature-2",
            text: "支持导入 / 导出 `.kmind-theme.json` 离线主题分享包。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.6.0-improvement-1",
            text: "保存或导入本地主题后，可以从导图内主题 Popover 应用到当前项目。"
          },
          {
            id: "obsidian-0.6.0-improvement-2",
            text: "项目设置新增紧凑、默认、舒展三档密度预设，用于快速调整导图间距。"
          },
          {
            id: "obsidian-0.6.0-improvement-3",
            text: "更新内核至 0.5.0，优化性能，修复主题间距隔离问题，并优化内核布局的纵向间距稳定性。"
          }
        ]
      }
    ]
  },
  {
    version: "0.5.0",
    releasedAt: "2026-05-09T00:00:00.000Z",
    locale: "zh-CN",
    title: "新增 Obsidian 插件快捷键配置，并且只作用于 KMind Zen 视图",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.5.0-feature-1",
            text: "新增 Obsidian 插件快捷键配置，并且只作用于 KMind Zen 视图。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.5.0-improvement-1",
            text: "快捷键面板新增富文本快捷键提示，覆盖节点正文、备注和批注编辑。"
          },
          {
            id: "obsidian-0.5.0-improvement-2",
            text: "右键菜单会在对应操作旁显示当前真实快捷键，包括用户自定义后的快捷键。"
          },
          {
            id: "obsidian-0.5.0-improvement-3",
            text: "补齐备注、批注、重置缩放、子导图和常用复制粘贴操作的默认快捷键。"
          }
        ]
      }
    ]
  },
  {
    version: "0.4.1",
    releasedAt: "2026-05-08T00:00:00.000Z",
    locale: "zh-CN",
    title: "将共享 KMind 内核升级到 0.4.0",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.4.1-improvement-1",
            text: "将共享 KMind 内核升级到 0.4.0。"
          },
          {
            id: "obsidian-0.4.1-improvement-2",
            text: "优化大图编辑体验，导图较大时浏览、缩放和渲染更顺滑。"
          },
          {
            id: "obsidian-0.4.1-improvement-3",
            text: "与 WebApp、思源插件同步最新性能优化。"
          }
        ]
      }
    ]
  },
  {
    version: "0.4.0",
    releasedAt: "2026-05-03T00:00:00.000Z",
    locale: "zh-CN",
    title: "重构 Project Popover，改为可视化布局卡片、明暗主题预览、彩虹连线设置、背景色预设和自定义颜色输入",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.4.0-improvement-1",
            text: "重构 Project Popover，改为可视化布局卡片、明暗主题预览、彩虹连线设置、背景色预设和自定义颜色输入。"
          },
          {
            id: "obsidian-0.4.0-improvement-2",
            text: "重构根节点“切换主题”Popover，用可视化卡片展示布局、主题和连线路由，方便用户在应用前比较效果。"
          },
          {
            id: "obsidian-0.4.0-improvement-3",
            text: "为 Obsidian 插件界面补齐布局、主题和连线路由的本地化展示名。"
          },
          {
            id: "obsidian-0.4.0-improvement-4",
            text: "将共享 KMind 内核升级到 0.3.0。"
          }
        ]
      }
    ]
  },
  {
    version: "0.3.1",
    releasedAt: "2026-05-02T00:00:00.000Z",
    locale: "zh-CN",
    title: "修复多选节点后的右键菜单行为：右键某个已选节点时，其它已选节点会继续保持选中态",
    tags: [
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.3.1-improvement-1",
            text: "节点右键菜单现在会以被右键的节点作为明确目标，覆盖复制、待办、子导图、展开和折叠等操作。"
          },
          {
            id: "obsidian-0.3.1-improvement-2",
            text: "保持删除行为与多选语义一致，从节点右键菜单删除时仍会删除当前选中的节点组。"
          }
        ]
      },
      {
        kind: "fix",
        title: "修复",
        items: [
          {
            id: "obsidian-0.3.1-fix-1",
            text: "修复多选节点后的右键菜单行为：右键某个已选节点时，其它已选节点会继续保持选中态。"
          }
        ]
      }
    ]
  },
  {
    version: "0.3.0",
    releasedAt: "2026-04-29T00:00:00.000Z",
    locale: "zh-CN",
    title: "通过共享 KMind 导入流程新增 XMind 文件导入支持",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.3.0-feature-1",
            text: "通过共享 KMind 导入流程新增 XMind 文件导入支持。"
          },
          {
            id: "obsidian-0.3.0-feature-2",
            text: "支持现代 `.xmind` 文件中的 `content.json`，包括主题树、自由主题、多画布项目、备注、标签、超链接、图片、关联线和概要。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.3.0-improvement-1",
            text: "导入前提示暂不支持的 XMind 特性；旧版 XML、加密文件或不支持的 zip 压缩方式会明确失败。"
          }
        ]
      }
    ]
  },
  {
    version: "0.2.0",
    releasedAt: "2026-04-29T00:00:00.000Z",
    locale: "zh-CN",
    title: "将共享 KMind 内核升级到 0.2.0",
    tags: [
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.2.0-improvement-1",
            text: "将共享 KMind 内核升级到 0.2.0。"
          }
        ]
      },
      {
        kind: "fix",
        title: "修复",
        items: [
          {
            id: "obsidian-0.2.0-fix-1",
            text: "修复极端情况下的化学方程式渲染问题，包括 mhchem 条件标签中包含中文时的显示异常。"
          }
        ]
      }
    ]
  },
  {
    version: "0.1.0",
    releasedAt: "2026-03-24T00:00:00.000Z",
    locale: "zh-CN",
    title: "准备 Obsidian 插件首个社区审核版本",
    tags: [
      "feature",
      "improvement",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "新增",
        items: [
          {
            id: "obsidian-0.1.0-feature-1",
            text: "新增仅发布流程，覆盖 `manifest.json`、`versions.json`、`README.md`、`CHANGELOG.md`、`LICENSE`、Git tag 和 GitHub Release 资源。"
          }
        ]
      },
      {
        kind: "improvement",
        title: "优化",
        items: [
          {
            id: "obsidian-0.1.0-improvement-1",
            text: "将插件生产构建对齐到 `https://kmind.app` 和生产签名公钥流程。"
          },
          {
            id: "obsidian-0.1.0-improvement-2",
            text: "将当前提交标记为仅支持桌面端。"
          }
        ]
      },
      {
        kind: "other",
        title: "其它",
        items: [
          {
            id: "obsidian-0.1.0-other-1",
            text: "准备 Obsidian 插件首个社区审核版本。"
          },
          {
            id: "obsidian-0.1.0-other-2",
            text: "补充插件市场审核所需的授权、网络使用、本地存储和 vault 文件访问说明。"
          }
        ]
      }
    ]
  }
];

export const OBSIDIAN_UPDATE_DIALOG_RELEASES_EN: KmindReleaseChangelogItem[] = [
  {
    version: "0.22.0",
    releasedAt: "2026-07-08T00:00:00.000Z",
    locale: "en-US",
    title: "Brace edge style and import/export updates",
    tags: [
      "feature",
      "fix",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "Added",
        items: [
          {
            id: "obsidian-0.22.0-brace-edge-style",
            text: "Added the brace edge style for all current layouts."
          },
          {
            id: "obsidian-0.22.0-structure-import-formats",
            text: "Added .md / .opml / .txt / .mm (FreeMind) file import support."
          },
          {
            id: "obsidian-0.22.0-structure-export-formats",
            text: "Added .md / .opml / .mm / .xmind file export support."
          }
        ]
      },
      {
        kind: "fix",
        title: "Fixed",
        items: [
          {
            id: "obsidian-0.22.0-remove-lecture-export-options",
            text: "Removed the not-yet-adapted lecture export options."
          }
        ]
      },
      {
        kind: "other",
        title: "Other",
        items: [
          {
            id: "obsidian-0.22.0-core-whiteboard-elements",
            text: "Updated the core version to prepare for upcoming whiteboard elements."
          },
          {
            id: "obsidian-0.22.0-core-performance",
            text: "Improved core performance."
          }
        ]
      }
    ]
  },
  {
    version: "0.21.0",
    releasedAt: "2026-07-03T00:00:00.000Z",
    locale: "en-US",
    title: "Node drag alignment guides",
    tags: [
      "feature",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "Added",
        items: [
          {
            id: "obsidian-0.21.0-node-drag-alignment-guides",
            text: "Added node drag alignment guides."
          }
        ]
      },
      {
        kind: "other",
        title: "Other",
        items: [
          {
            id: "obsidian-0.21.0-core-whiteboard-elements",
            text: "Updated the core version to prepare for upcoming whiteboard elements."
          }
        ]
      }
    ]
  },
  {
    version: "0.20.0",
    releasedAt: "2026-06-29T00:00:00.000Z",
    locale: "en-US",
    title: "Wheel behavior preference",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "Added",
        items: [
          {
            id: "obsidian-0.20.0-wheel-behavior-setting",
            text: "Added Wheel behavior under Plugin settings -> Canvas interaction, with Zoom directly, Pan with wheel and Ctrl/Cmd to zoom, and Disable wheel zoom options."
          },
          {
            id: "obsidian-0.20.0-wheel-pan-mode",
            text: "In Pan with wheel mode, vertical wheel pans up/down, horizontal wheel or Shift + vertical wheel pans left/right, and Ctrl/Cmd + wheel zooms."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.20.0-wheel-default",
            text: "The default wheel behavior stays as direct zoom, preserving existing user habits."
          }
        ]
      }
    ]
  },
  {
    version: "0.19.0",
    releasedAt: "2026-06-28T00:00:00.000Z",
    locale: "en-US",
    title: "Branch Line and tree layouts",
    tags: [
      "feature",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "Added",
        items: [
          {
            id: "obsidian-0.19.0-tree-layouts",
            text: "Added layouts: Tree Up & Tree Down."
          },
          {
            id: "obsidian-0.19.0-ink-branch-theme",
            text: "Added minimal theme: Ink Branch.",
            media: [
              {
                type: "png",
                url: "https://s312g.malibu.root233.com/picbed/2026/06/98fe914a43cd46effe1079193f2a4697.png",
                posterUrl: "https://s312g.malibu.root233.com/picbed/2026/06/98fe914a43cd46effe1079193f2a4697.png",
                alt: "Ink Branch theme preview"
              }
            ]
          },
          {
            id: "obsidian-0.19.0-branch-line-route",
            text: "Added edge style: Branch Line. It is also available in Theme Designer."
          }
        ]
      },
      {
        kind: "other",
        title: "Other",
        items: [
          {
            id: "obsidian-0.19.0-core-layout-engine",
            text: "Updated the core layout engine."
          }
        ]
      }
    ]
  },
  {
    version: "0.18.0",
    releasedAt: "2026-06-27T00:00:00.000Z",
    locale: "en-US",
    title: "Node structure shortcuts",
    tags: [
      "feature",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "Added",
        items: [
          {
            id: "obsidian-0.18.0-add-parent-context-menu",
            text: "Added Add Parent to the node context menu and shortcut settings."
          },
          {
            id: "obsidian-0.18.0-move-node-shortcuts",
            text: "Added Move Node Up and Move Node Down with `Alt/Option+Up` and `Alt/Option+Down`."
          },
          {
            id: "obsidian-0.18.0-collapse-expand-shortcuts",
            text: "Added Collapse and Expand shortcuts: `Alt/Option+Left` and `Alt/Option+Right`."
          }
        ]
      },
      {
        kind: "other",
        title: "Other",
        items: [
          {
            id: "obsidian-0.18.0-core-version",
            text: "Updated the core version."
          }
        ]
      }
    ]
  },
  {
    version: "0.17.1",
    releasedAt: "2026-06-25T00:00:00.000Z",
    locale: "en-US",
    title: "Update dialog official content loading fix",
    tags: [
      "fix"
    ],
    sections: [
      {
        kind: "fix",
        title: "Fixes",
        items: [
          {
            id: "obsidian-0.17.1-official-content-cors",
            text: "Fix official content loading in the Obsidian update dialog when the plugin requests KMind service content from the Obsidian app origin."
          }
        ]
      }
    ]
  },
  {
    version: "0.17.0",
    releasedAt: "2026-06-25T00:00:00.000Z",
    locale: "en-US",
    title: "Update dialog and shortcut refinement",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.17.0-update-dialog-and-changelog",
            text: "Add the update dialog and official changelog, including support for viewing the current release and past updates."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improvements",
        items: [
          {
            id: "obsidian-0.17.0-remove-plugin-ctrl-n",
            text: "Remove the plugin-side Ctrl/Cmd+N default shortcut to avoid overriding Obsidian or system new-item behavior."
          }
        ]
      }
    ]
  },
  {
    version: "0.16.0",
    releasedAt: "2026-06-23T00:00:00.000Z",
    locale: "en-US",
    title: "True In-place Node Editing",
    tags: [
      "feature",
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "feature",
        title: "Node editing",
        items: [
          {
            id: "obsidian-0.16.0-inline-node-editing",
            text: "Reworked node editing into true in-place editing, keeping the editing area inside the node body for a smoother and more stable experience."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Editing experience",
        items: [
          {
            id: "obsidian-0.16.0-first-line-multiline-zoom",
            text: "Improved editing interaction and performance, especially around first-line input, multi-line growth, zoom, and mixed text sizes."
          },
          {
            id: "obsidian-0.16.0-disable-spellcheck",
            text: "Disabled spell checking in node body editing, notes, and Outline mode to reduce browser or host writing-assistant interference."
          }
        ]
      },
      {
        kind: "fix",
        title: "Export stability",
        items: [
          {
            id: "obsidian-0.16.0-export-text-clipping",
            text: "Fixed edge cases where exported PNG or SVG files could clip node body text."
          }
        ]
      }
    ]
  },
  {
    version: "0.15.0",
    releasedAt: "2026-06-22T00:00:00.000Z",
    locale: "en-US",
    title: "Add node width resize handles so node content width can be adjusted directly on the canvas",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.15.0-feature-1",
            text: "Add node width resize handles so node content width can be adjusted directly on the canvas."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.15.0-improvement-1",
            text: "Improve edge-case node width measurement to prevent node content from being clipped in dense text, formula, inline code, and export scenarios."
          }
        ]
      }
    ]
  },
  {
    version: "0.14.1",
    releasedAt: "2026-06-22T00:00:00.000Z",
    locale: "en-US",
    title: "Align the Obsidian Outline and Split row controls with the web app by removing the host button background and inset shadows",
    tags: [
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.14.1-improvement-1",
            text: "Align the Obsidian Outline and Split row controls with the web app by removing the host button background and inset shadows."
          }
        ]
      },
      {
        kind: "fix",
        title: "Fixed",
        items: [
          {
            id: "obsidian-0.14.1-fix-1",
            text: "Fix Outline row context menus inside Obsidian so they open next to the row instead of drifting to the far right."
          }
        ]
      }
    ]
  },
  {
    version: "0.14.0",
    releasedAt: "2026-06-20T00:00:00.000Z",
    locale: "en-US",
    title: "Add Outline and Split modes alongside the map view",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.14.0-feature-1",
            text: "Add Outline and Split modes alongside the map view."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.14.0-improvement-1",
            text: "Edit the same mind map as a continuous outline while keeping selection, rich text, summaries, icons, and shortcuts synchronized with the map."
          },
          {
            id: "obsidian-0.14.0-improvement-2",
            text: "Drag nodes between the map and outline in Split mode, including outline-to-map and map-to-outline moves."
          }
        ]
      }
    ]
  },
  {
    version: "0.13.0",
    releasedAt: "2026-06-14T00:00:00.000Z",
    locale: "en-US",
    title: "Improve the node relationship line editor and smart avoidance behavior",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.13.0-feature-1",
            text: "Add three relationship line types: straight, orthogonal, and rounded orthogonal."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.13.0-improvement-1",
            text: "Improve the node relationship line editor and smart avoidance behavior."
          }
        ]
      }
    ]
  },
  {
    version: "0.12.1",
    releasedAt: "2026-06-12T00:00:00.000Z",
    locale: "en-US",
    title: "Fix the Todo context-menu shortcut hint",
    tags: [
      "fix"
    ],
    sections: [
      {
        kind: "fix",
        title: "Fixed",
        items: [
          {
            id: "obsidian-0.12.1-fix-1",
            text: "Fix the Todo context-menu shortcut hint."
          }
        ]
      }
    ]
  },
  {
    version: "0.12.0",
    releasedAt: "2026-06-12T00:00:00.000Z",
    locale: "en-US",
    title: "Add right-click actions to expand a node or the current map to 1-6 levels",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.12.0-feature-1",
            text: "Add right-click actions to expand a node or the current map to 1-6 levels."
          },
          {
            id: "obsidian-0.12.0-feature-2",
            text: "Add quick expand/collapse actions for node subtrees and the current map."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.12.0-improvement-1",
            text: "Keep the current-map menu switching between collapse and expand after the map is collapsed."
          }
        ]
      }
    ]
  },
  {
    version: "0.11.2",
    releasedAt: "2026-06-04T00:00:00.000Z",
    locale: "en-US",
    title: "Update the marketplace manifest description",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.11.2-improvement-1",
            text: "Update the marketplace manifest description"
          }
        ]
      }
    ]
  },
  {
    version: "0.11.1",
    releasedAt: "2026-06-03T00:00:00.000Z",
    locale: "en-US",
    title: "Improve Obsidian plugin copy",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.11.1-improvement-1",
            text: "Improve Obsidian plugin copy."
          },
          {
            id: "obsidian-0.11.1-improvement-2",
            text: "Improve quick-start and marketplace-facing guidance."
          },
          {
            id: "obsidian-0.11.1-improvement-3",
            text: "Polish interaction copy and plugin presentation details."
          }
        ]
      }
    ]
  },
  {
    version: "0.11.0",
    releasedAt: "2026-05-21T00:00:00.000Z",
    locale: "en-US",
    title: "Add a canvas drag habit setting with Pan-first and Select-first modes",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.11.0-feature-1",
            text: "Add a canvas drag habit setting with Pan-first and Select-first modes."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.11.0-improvement-1",
            text: "In Select-first mode, drag blank map space to marquee-select and hold Space while dragging to pan."
          },
          {
            id: "obsidian-0.11.0-improvement-2",
            text: "Keep Space reserved for canvas navigation so custom shortcuts do not interfere with panning."
          }
        ]
      }
    ]
  },
  {
    version: "0.10.0",
    releasedAt: "2026-05-21T00:00:00.000Z",
    locale: "en-US",
    title: "Add automatic image compression for inserted images in the plugin, enabled by default",
    tags: [
      "feature"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.10.0-feature-1",
            text: "Add automatic image compression for inserted images in the plugin, enabled by default."
          },
          {
            id: "obsidian-0.10.0-feature-2",
            text: "Add direct node-image resizing."
          },
          {
            id: "obsidian-0.10.0-feature-3",
            text: "Add drag-and-drop node-image positioning across top, bottom, left, and right slots."
          }
        ]
      }
    ]
  },
  {
    version: "0.9.1",
    releasedAt: "2026-05-20T00:00:00.000Z",
    locale: "en-US",
    title: "Improve dark-mode editing for nodes and rich-text notes",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.9.1-improvement-1",
            text: "Improve dark-mode editing for nodes and rich-text notes."
          },
          {
            id: "obsidian-0.9.1-improvement-2",
            text: "Improve dark-mode adaptation for rich-text toolbar dropdowns, link/cloze/slash/formula popovers, and context-menu scrollbars."
          },
          {
            id: "obsidian-0.9.1-improvement-3",
            text: "Improve dark-mode adaptation for relationship-line creation and format-painter cursor-following hints."
          }
        ]
      }
    ]
  },
  {
    version: "0.9.0",
    releasedAt: "2026-05-18T00:00:00.000Z",
    locale: "en-US",
    title: "Improve summary node localization and interaction details",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.9.0-feature-1",
            text: "Add bulk node dragging: after multi-selecting nodes, drag any selected node to move them together."
          },
          {
            id: "obsidian-0.9.0-feature-2",
            text: "Add automatic node centering when a map is first created."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.9.0-improvement-1",
            text: "Improve summary node localization and interaction details."
          }
        ]
      }
    ]
  },
  {
    version: "0.8.0",
    releasedAt: "2026-05-18T00:00:00.000Z",
    locale: "en-US",
    title: "Improve relationship line editing and interactions, with new dashed and dotted line styles",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.8.0-feature-1",
            text: "Add relationship line color configuration for clearer cross-branch structure."
          },
          {
            id: "obsidian-0.8.0-feature-2",
            text: "Add project-level relationship line settings so maps can keep a consistent relationship style."
          },
          {
            id: "obsidian-0.8.0-feature-3",
            text: "Add relationship line support for summaries."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.8.0-improvement-1",
            text: "Improve relationship line editing and interactions, with new dashed and dotted line styles."
          }
        ]
      }
    ]
  },
  {
    version: "0.7.0",
    releasedAt: "2026-05-17T00:00:00.000Z",
    locale: "en-US",
    title: "Add polished PNG export with the currently available clean window frame style",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.7.0-feature-1",
            text: "Add polished PNG export with the currently available clean window frame style."
          },
          {
            id: "obsidian-0.7.0-feature-2",
            text: "Add PNG clarity options in the export dialog so exported images can balance size and sharpness."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.7.0-improvement-1",
            text: "Improve the canvas and node \"Copy as image\" context menu with visual style previews for original and window-framed images."
          },
          {
            id: "obsidian-0.7.0-improvement-2",
            text: "Improve context-menu submenu hover tolerance."
          }
        ]
      }
    ]
  },
  {
    version: "0.6.0",
    releasedAt: "2026-05-15T00:00:00.000Z",
    locale: "en-US",
    title: "Design and save local KMind Zen themes directly inside the Obsidian plugin",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.6.0-improvement-1",
            text: "Design and save local KMind Zen themes directly inside the Obsidian plugin."
          },
          {
            id: "obsidian-0.6.0-improvement-2",
            text: "Import and export `.kmind-theme.json` packages for offline theme sharing."
          },
          {
            id: "obsidian-0.6.0-improvement-3",
            text: "Apply local themes from the map theme popover after saving or importing them."
          },
          {
            id: "obsidian-0.6.0-improvement-4",
            text: "Use compact, default, and relaxed project density presets to adjust map spacing quickly."
          },
          {
            id: "obsidian-0.6.0-improvement-5",
            text: "Upgrade the shared KMind core to 0.5.0, improve performance, fix theme spacing isolation, and improve core-layout vertical spacing stability."
          }
        ]
      }
    ]
  },
  {
    version: "0.5.0",
    releasedAt: "2026-05-09T00:00:00.000Z",
    locale: "en-US",
    title: "Add shortcut customization in the Obsidian plugin settings, scoped to KMind Zen views",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.5.0-feature-1",
            text: "Add shortcut customization in the Obsidian plugin settings, scoped to KMind Zen views."
          },
          {
            id: "obsidian-0.5.0-feature-2",
            text: "Add a rich-text shortcut reference for node text, notes, and comments."
          },
          {
            id: "obsidian-0.5.0-feature-3",
            text: "Add more default shortcuts for notes, comments, zoom reset, submaps, and common copy/paste actions."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.5.0-improvement-1",
            text: "Show the current shortcut next to supported context-menu actions, including custom bindings."
          }
        ]
      }
    ]
  },
  {
    version: "0.4.1",
    releasedAt: "2026-05-08T00:00:00.000Z",
    locale: "en-US",
    title: "Upgrade the shared KMind core to 0.4.0",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.4.1-improvement-1",
            text: "Upgrade the shared KMind core to 0.4.0."
          },
          {
            id: "obsidian-0.4.1-improvement-2",
            text: "Improve the large-map editing experience, including smoother viewing, zooming, and rendering in the Obsidian view."
          },
          {
            id: "obsidian-0.4.1-improvement-3",
            text: "Align the Obsidian plugin with the latest web and SiYuan performance improvements."
          }
        ]
      }
    ]
  },
  {
    version: "0.4.0",
    releasedAt: "2026-05-03T00:00:00.000Z",
    locale: "en-US",
    title: "Redesign the Project Popover with visual layout cards, light/dark theme previews, rainbow edge settings, and background color presets plus custom color input",
    tags: [
      "improvement"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.4.0-improvement-1",
            text: "Redesign the Project Popover with visual layout cards, light/dark theme previews, rainbow edge settings, and background color presets plus custom color input."
          },
          {
            id: "obsidian-0.4.0-improvement-2",
            text: "Redesign the root-node theme switching popover with visual layout, theme, and edge route previews, making layout and line style changes easier to compare before applying."
          },
          {
            id: "obsidian-0.4.0-improvement-3",
            text: "Localize layout, theme, and edge route display names across the Obsidian plugin UI."
          },
          {
            id: "obsidian-0.4.0-improvement-4",
            text: "Upgrade the shared KMind core to 0.3.0."
          }
        ]
      }
    ]
  },
  {
    version: "0.3.1",
    releasedAt: "2026-05-02T00:00:00.000Z",
    locale: "en-US",
    title: "Fix node context menu behavior after multi-selecting nodes: right-clicking an already selected node now keeps the full multi-selection highlighted",
    tags: [
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.3.1-improvement-1",
            text: "Make node context menu actions use the node that was right-clicked as their explicit target, including copy, todo, submap, expand, and collapse actions."
          },
          {
            id: "obsidian-0.3.1-improvement-2",
            text: "Keep delete behavior aligned with multi-selection, so deleting from the node context menu still deletes the selected node group."
          }
        ]
      },
      {
        kind: "fix",
        title: "Fixed",
        items: [
          {
            id: "obsidian-0.3.1-fix-1",
            text: "Fix node context menu behavior after multi-selecting nodes: right-clicking an already selected node now keeps the full multi-selection highlighted."
          }
        ]
      }
    ]
  },
  {
    version: "0.3.0",
    releasedAt: "2026-04-29T00:00:00.000Z",
    locale: "en-US",
    title: "Add XMind file import support through the shared KMind import flow",
    tags: [
      "feature",
      "improvement"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.3.0-feature-1",
            text: "Add XMind file import support through the shared KMind import flow."
          },
          {
            id: "obsidian-0.3.0-feature-2",
            text: "Support modern `.xmind` files with `content.json`, including topic trees, free topics, multi-sheet projects, notes, labels, hyperlinks, images, relationships, and summaries."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.3.0-improvement-1",
            text: "Report unsupported XMind features before import, and fail clearly for legacy XML, encrypted files, or unsupported zip compression."
          }
        ]
      }
    ]
  },
  {
    version: "0.2.0",
    releasedAt: "2026-04-29T00:00:00.000Z",
    locale: "en-US",
    title: "Upgrade the shared KMind core to 0.2.0",
    tags: [
      "improvement",
      "fix"
    ],
    sections: [
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.2.0-improvement-1",
            text: "Upgrade the shared KMind core to 0.2.0."
          }
        ]
      },
      {
        kind: "fix",
        title: "Fixed",
        items: [
          {
            id: "obsidian-0.2.0-fix-1",
            text: "Fix chemical equation rendering in extreme cases, including mhchem labels that contain CJK text."
          }
        ]
      }
    ]
  },
  {
    version: "0.1.0",
    releasedAt: "2026-03-24T00:00:00.000Z",
    locale: "en-US",
    title: "Prepare the initial Obsidian plugin release for community review",
    tags: [
      "feature",
      "improvement",
      "other"
    ],
    sections: [
      {
        kind: "feature",
        title: "New",
        items: [
          {
            id: "obsidian-0.1.0-feature-1",
            text: "Add a release-only publishing flow for `manifest.json`, `versions.json`, `README.md`, `CHANGELOG.md`, `LICENSE`, Git tag, and GitHub Release assets."
          },
          {
            id: "obsidian-0.1.0-feature-2",
            text: "Add marketplace review disclosures for licensing, network use, local storage, and vault file access."
          }
        ]
      },
      {
        kind: "improvement",
        title: "Improved",
        items: [
          {
            id: "obsidian-0.1.0-improvement-1",
            text: "Align the plugin production build with `https://kmind.app` and the production signing public key flow."
          }
        ]
      },
      {
        kind: "other",
        title: "Other",
        items: [
          {
            id: "obsidian-0.1.0-other-1",
            text: "Prepare the initial Obsidian plugin release for community review."
          },
          {
            id: "obsidian-0.1.0-other-2",
            text: "Mark the current submission as desktop-only."
          }
        ]
      }
    ]
  }
];
