export const KMIND_ZEN_AUTO_HISTORY_MIN_INTERVAL_MS = 5 * 60 * 1000;
export const KMIND_ZEN_AUTO_HISTORY_KEEP = 5;

export const KMIND_ZEN_AUTO_HISTORY_MIN_INTERVAL_MINUTES = Math.round(KMIND_ZEN_AUTO_HISTORY_MIN_INTERVAL_MS / 60_000);

